name: build

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install  dependencies
        run: pnpm install
      - name: Test  code
        run: pnpm test
      - name: Generate  bundle
        run: pnpm build
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
