# on: ['push', 'pull_request']
on:
  push:
    tags:
      - 'v*.*.*'

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install  dependencies
        run: pnpm install
      - name: Test  code
        run: pnpm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
